### PR TITLE
finish fig6

### PR DESCRIPTION
**Pull request by BCCghspace**
Hi Anna, I just finished everything up to figure6. Check it out :)

### CODE REVIEW

**Comment by annaduan09** [comment]
Hi Bingchu,

This is great - thanks for your work! One thing - I'm concerned because in the book it says to choose something that faces more reporting bias than burglary. I think robbery might be too similar. Perhaps we could do something like arrests? I say this because I know that arrests happen more in places that are more heavily policed, and give the impression that there is more crime in these areas.

What do you think? Also, are you free to meet tonight?

Best,
Anna

**Comment by BCCghspace** [comment]
I think that’s a great idea! Let’s change to that :D

**Comment by annaduan09** [comment]
Great! I'm on it. Here's a link if 11 still works: 

Join Zoom Meeting
https://zoom.us/j/3426927206?pwd=Q3hMWVlFZXJtN21NR2FrclJqUzcxQT09

Meeting ID: 342 692 7206
Passcode: 7PCv2m

Best,
Anna

**Comment by BCCghspace** [comment]
Oh sorry I just saw this email. See you tomorrow :)

**Pull request merged**
